# Dependencies
markdown:         kramdown
highlighter:      rouge

- type: picture-glance
  entity: person.david
  entities:
    - entity: device_tracker.smartphone_david_wifi
      icon: mdi:cellphone-wireless
    - entity: device_tracker.smartphone_david_bt
      icon: mdi:bluetooth
  state_image:
    "home": /local/images/David.JPG
    "not_home": /local/images/David_bw.JPG
  title: "David"
avatar:           "/assest/css/pic.jpg"

# Setup
title:            Xun Zhong
tagline:          'Homepage'
description:      'Software Engineering | Linguistics | Business | Music | Communication'
url:              https://peggiezx.github.io/
baseurl:          '/'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'peggiezx'
  url:            https://peggiezx.github.io/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
